### PR TITLE
GitHub actions artifact publishing

### PR DESCRIPTION
**Pull request by Michael7371**
Adding a GitHub Action to publish java artifacts to GitHub's hosted Maven Central.

### CODE REVIEW

**Review by dmccoystephenson — CHANGES_REQUESTED** [review]
Has this been tested? I am not seeing an artifact on this repository.

**Comment by Michael7371** [comment]
> Has this been tested? I am not seeing an artifact on this repository.

Here's a link: https://github.com/CDOT-CV/jpo-sdw-depositor/packages/2215740
I am not sure why it doesn't show up on the repository view.

**Review by dmccoystephenson — APPROVED** [review]
Looks good to me!

**Review by drewjj — APPROVED** [review]
Looks good to me

**Pull request merged**
